// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrugnbtxiakihtxfrhwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydWduYnR4aWFraWh0eGZyaHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTQ0NDUsImV4cCI6MjA1Nzk5MDQ0NX0.z_B1j07gATTIwdyuyEBlqAN4DX818JLrLUfz5iHORNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);