// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnqqtvzpvvohaqqjmxrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhucXF0dnpwdnZvaGFxcWpteHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NzA4ODgsImV4cCI6MjA1NjU0Njg4OH0.TwZcMhUdIXiXlx8sYn0XOK8wjgk-8kDtTLTmIe1J8zE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);